version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=supersecretkey
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  web:
    build:
      context: ./web
    ports:
      - "8200:80"
    depends_on:
      - api

volumes:
  mongodb_data: 